services:
  sionna-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerpaw-sionna-api
    gpus: all
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
