services:
  aerpaw-sionna-api:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    container_name: aerpaw-sionna-api
    gpus: all
    cap_add:
      - NET_ADMIN
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    environment:
      - PYTHONPATH=/app/src
      - SCENE_PATH=/app/scenes/lake-wheeler-scene.xml
      - MI_VARIANT=${MI_VARIANT:-cuda_ad_mono_polarized}
      - SIONNA_MERGE_SHAPES=${SIONNA_MERGE_SHAPES:-true}
    restart: unless-stopped
